name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      # Install dependencies safely
      - name: Install dependencies
        run: npm ci || npm install

      # Fix missing Rollup binary issue
      - name: Ensure Rollup native binary exists
        run: npm install @rollup/rollup-linux-x64-gnu --no-save

      # Type check
      - name: Run TypeScript type checking
        run: npm run type-check

      # Lint
      - name: Run ESLint
        run: npm run lint

      # Check Prettier formatting
      - name: Check Prettier formatting
        run: npm run format:check

      # Run tests with Vitest
      - name: Run Vitest tests
        run: npm run test:run -- --reporter=verbose --coverage
